version: "3.9"
   
services: 
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app
    ports:
      - "8000:8000" 
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=staff_system_db_main_1
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
      - ALLOWED_HOSTS=*
      - SECRET_KEY=vvno_hiu+6-qbv8+4_kxly8@6@a9#(_681ewc&)fe*75u-j6+j 
    depends_on:
        - db 
  db:
    image: postgres:14.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=staff_system_db_main_1
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432" 
  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A configuration worker --loglevel=info --without-gossip --without-mingle --without-heartbeat -Ofair
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=staff_system_db_main_1
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
      - ALLOWED_HOSTS=*
      - SECRET_KEY=vvno_hiu+6-qbv8+4_kxly8@6@a9#(_681ewc&)fe*75u-j6+j 
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A configuration beat -l info
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=staff_system_db_main_1
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
      - ALLOWED_HOSTS=*
      - SECRET_KEY=vvno_hiu+6-qbv8+4_kxly8@6@a9#(_681ewc&)fe*75u-j6+j 
    depends_on:
      - redis
      - web

networks:
    djangonetwork:
      driver: bridge
