# Generated by Django 4.0.3 on 2022-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_date_joined_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hiring_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('0', 'General Director'), ('1', 'Main Manager'), ('2', 'Middle Manager'), ('3', 'Lower Middle Manager'), ('4', 'Lower Manager')], max_length=30, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_information',
            field=models.IntegerField(null=True, verbose_name='salary information'),
        ),
    ]
