# Generated by Django 4.0.3 on 2022-04-10 06:14

import apps.api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_full_name_alter_user_hiring_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.api.models.UserManager()),
            ],
        ),
    ]
